#!/usr/bin/env bash
case "$1" in
  start)
    if [ -f /var/run/my_process.pid ]; then
      echo "manage_my_process is already running."
      exit 1
    fi

    ./manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process started."
    ;;

  stop)
    if [ -f /var/run/my_process.pid ]; then
      pid=$(cat /var/run/my_process.pid)
      kill $pid
      rm /var/run/my_process.pid
      echo "manage_my_process stopped."
    else
      echo "manage_my_process is not running."
      exit 1
    fi
    ;;

  restart)
    if [ -f /var/run/my_process.pid ]; then
      pid=$(cat /var/run/my_process.pid)
      kill $pid
      rm /var/run/my_process.pid
      echo "manage_my_process stopped."
    else
      echo "manage_my_process is not running."
    fi

    ./manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process restarted."
    ;;

  *)
    echo "Usage: manage_my_process {start|stop|restart}"
    exit 1
    ;;
esac
